# Generated by Django 5.1 on 2024-08-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sexe', models.BooleanField(default=False)),
                ('date_de_naissance', models.CharField(max_length=255)),
                ('matiere', models.CharField(choices=[('MATH', 'MATHEMATIQUE'), ('PHY', 'PHYSIQUE'), ('SVT', 'SVT')], max_length=25)),
                ('numero_de_telephone', models.CharField(max_length=15)),
                ('ville', models.CharField(max_length=15)),
                ('vacant', models.BooleanField(default=False)),
            ],
        ),
    ]
