# Generated by Django 5.1 on 2024-08-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sexe', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
                ('date_naissance', models.CharField(max_length=255)),
                ('numero_telephone', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
            ],
        ),
    ]
