# Generated by Django 5.1 on 2024-08-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
